import type { TranslationObject } from '@ngx-translate/core';

import type { LocaleCode } from './models/locale.model';

export const PLATFORM_TRANSLATIONS: Readonly<Record<LocaleCode, TranslationObject>> = {
  en: {
    header: { primaryNavigation: 'Primary navigation', projects: 'Projects', engineering: 'Engineering', about: 'About' },
    meta: { titleTemplate: '{{title}} · YARP.DEV' },
    home: {
      metaTitle: 'Engineering, products and technical documentation', heroEyebrow: 'Software engineering in public', heroTitle: 'Engineering real products, not demo projects.', heroLede: 'Production-minded .NET engineering, domain architecture, product development and technical documentation — demonstrated through real systems and engineering decisions.', exploreProjects: 'Explore Projects', exploreEngineering: 'Explore Engineering', readDocs: 'Read YARP Documentation', projectsEyebrow: 'Products', projectsTitle: 'Systems built around real domains.', viewProject: 'View project', engineeringEyebrow: 'Engineering focus', engineeringTitle: 'Architecture is visible in the work.', practiceEyebrow: 'Engineering in practice', practiceTitle: 'From problem framing to operations.', docsEyebrow: 'Documentation', docsTitle: 'Documentation is part of the engineering output.', docsBody: 'YARP.DEV keeps the existing Microsoft YARP guides first-class while adding curated product architecture and engineering material around them.', exploreDocs: 'Explore Documentation', footerAttribution: 'Microsoft YARP documentation is adapted from Microsoft Learn under CC BY 4.0. YARP.DEV is an independent engineering/documentation site.', footerSourceProject: 'Microsoft YARP on GitHub ↗', focusBackend: '.NET & backend', focusBackendBody: 'ASP.NET Core · EF Core · Aspire · OpenTelemetry · PostgreSQL · SQL Server', focusArchitecture: 'Architecture', focusArchitectureBody: 'DDD · CQRS · Modular Monolith · Vertical Slice · bounded contexts', focusProducts: 'Products & UX', focusProductsBody: 'Blazor · MAUI · enterprise workflows · multi-tenancy · compliance systems', focusAi: 'AI infrastructure', focusAiBody: 'AI gateways · local models · cloud fallback · RAG · tools · observability'
    },
    process: { aria: 'Problem to operations engineering flow', problem: 'Problem', domain: 'Domain', architecture: 'Architecture', ux: 'UX', api: 'API', implementation: 'Implementation', tests: 'Tests', operations: 'Operations' },
    projects: { metaTitle: 'Projects', eyebrow: 'Product engineering', title: 'Projects', lede: 'A portfolio of real product domains, architecture decisions and implementation work — presented as systems rather than a list of technologies.', problem: 'Problem', architecture: 'Architecture', viewProject: 'View project' },
    projectDetail: { allProjects: 'All projects', technicalDocs: 'Technical Documentation', problem: 'Problem', problemTitle: 'What the product is solving', users: 'Users', usersTitle: 'Who the system serves', architecture: 'Architecture', architectureTitle: 'How the system is shaped', patterns: 'Patterns & boundaries', frontend: 'Frontend', backend: 'Backend', infrastructure: 'Infrastructure', engineering: 'Engineering highlights', engineeringTitle: 'Problems worth showing' },
    engineering: { metaTitle: 'Engineering', eyebrow: 'Engineering practice', title: 'Architecture through working systems.', lede: 'The focus is not a CV-style technology inventory. The work shows how domain modelling, modern .NET, reliability, frontend architecture and AI-assisted development fit together in production-minded systems.', practiceEyebrow: 'Delivery model', practiceTitle: 'Engineering as a connected system.', architectureCard: 'Architecture', architectureBody: 'DDD · CQRS · Modular Monolith · Vertical Slice · bounded contexts', dotnetCard: '.NET', dotnetBody: 'ASP.NET Core · EF Core · Blazor · MAUI · Aspire · OpenTelemetry', reliabilityCard: 'Reliability', reliabilityBody: 'Result Pattern · idempotency · optimistic concurrency · outbox · resilience · observability', qualityCard: 'Code quality', qualityBody: 'Clean Code · KISS · YAGNI · DRY · modern C# · BCL-first engineering', aiCard: 'AI-assisted engineering', aiBody: 'Architecture rules · agents · automated review · documentation-assisted implementation · controlled code generation', yarpCard: 'YARP Reverse Proxy', yarpBody: 'Routing · transforms · authentication & authorization · health checks · forwarding · diagnostics' },
    about: { metaTitle: 'About', eyebrow: 'About', title: 'Software Engineer / .NET Architect', lede: 'Backend and full-stack engineering focused on explicit domain boundaries, maintainable architecture and production-oriented software.', focus: 'Focus', focusBody: '.NET backend systems · domain architecture · SaaS · compliance · distributed systems · AI infrastructure · cross-platform .NET', principles: 'Engineering principles', principlesBody: 'Simple code · explicit domain boundaries · documentation-driven development · testable vertical slices · pragmatic use of AI', statement: 'The goal is simple: make the architecture understandable in the code, the product understandable in the UX, and the engineering decisions understandable in the documentation.' }
  },
  bg: {
    header: { primaryNavigation: 'Основна навигация', projects: 'Проекти', engineering: 'Инженеринг', about: 'За мен' },
    meta: { titleTemplate: '{{title}} · YARP.DEV' },
    home: {
      metaTitle: 'Инженеринг, продукти и техническа документация', heroEyebrow: 'Софтуерен инженеринг публично', heroTitle: 'Реални продукти, не demo проекти.', heroLede: 'Production-minded .NET инженеринг, домейн архитектура, продуктова разработка и техническа документация — показани чрез реални системи и инженерни решения.', exploreProjects: 'Разгледай проектите', exploreEngineering: 'Разгледай инженеринга', readDocs: 'YARP документация', projectsEyebrow: 'Продукти', projectsTitle: 'Системи, изградени около реални домейни.', viewProject: 'Виж проекта', engineeringEyebrow: 'Инженерен фокус', engineeringTitle: 'Архитектурата се вижда в работата.', practiceEyebrow: 'Инженеринг на практика', practiceTitle: 'От дефинирането на проблема до operations.', docsEyebrow: 'Документация', docsTitle: 'Документацията е част от инженерния резултат.', docsBody: 'YARP.DEV запазва съществуващите ръководства за Microsoft YARP като първокласна част от сайта и добавя подбрано съдържание за продуктова архитектура и инженеринг.', exploreDocs: 'Разгледай документацията', footerAttribution: 'Документацията за Microsoft YARP е адаптирана от Microsoft Learn под CC BY 4.0. YARP.DEV е независим инженерен и документационен сайт.', footerSourceProject: 'Microsoft YARP в GitHub ↗', focusBackend: '.NET и backend', focusBackendBody: 'ASP.NET Core · EF Core · Aspire · OpenTelemetry · PostgreSQL · SQL Server', focusArchitecture: 'Архитектура', focusArchitectureBody: 'DDD · CQRS · Modular Monolith · Vertical Slice · bounded contexts', focusProducts: 'Продукти и UX', focusProductsBody: 'Blazor · MAUI · enterprise процеси · multi-tenancy · compliance системи', focusAi: 'AI инфраструктура', focusAiBody: 'AI gateways · локални модели · cloud fallback · RAG · инструменти · observability'
    },
    process: { aria: 'Инженерен процес от проблем до операции', problem: 'Проблем', domain: 'Домейн', architecture: 'Архитектура', ux: 'UX', api: 'API', implementation: 'Имплементация', tests: 'Тестове', operations: 'Операции' },
    projects: { metaTitle: 'Проекти', eyebrow: 'Продуктов инженеринг', title: 'Проекти', lede: 'Портфолио от реални продуктови домейни, архитектурни решения и implementation работа — представени като системи, а не като списък от технологии.', problem: 'Проблем', architecture: 'Архитектура', viewProject: 'Виж проекта' },
    projectDetail: { allProjects: 'Всички проекти', technicalDocs: 'Техническа документация', problem: 'Проблем', problemTitle: 'Какво решава продуктът', users: 'Потребители', usersTitle: 'За кого е системата', architecture: 'Архитектура', architectureTitle: 'Как е структурирана системата', patterns: 'Patterns и граници', frontend: 'Frontend', backend: 'Backend', infrastructure: 'Инфраструктура', engineering: 'Инженерни акценти', engineeringTitle: 'Проблеми, които си струва да бъдат показани' },
    engineering: { metaTitle: 'Инженеринг', eyebrow: 'Инженерна практика', title: 'Архитектура чрез работещи системи.', lede: 'Фокусът не е CV-списък с технологии. Проектите показват как домейн моделирането, модерният .NET, надеждността, frontend архитектурата и AI-assisted development работят заедно в production-minded системи.', practiceEyebrow: 'Модел на изпълнение', practiceTitle: 'Инженерингът като свързана система.', architectureCard: 'Архитектура', architectureBody: 'DDD · CQRS · Modular Monolith · Vertical Slice · bounded contexts', dotnetCard: '.NET', dotnetBody: 'ASP.NET Core · EF Core · Blazor · MAUI · Aspire · OpenTelemetry', reliabilityCard: 'Надеждност', reliabilityBody: 'Result Pattern · идемпотентност · optimistic concurrency · outbox · resilience · observability', qualityCard: 'Качество на кода', qualityBody: 'Clean Code · KISS · YAGNI · DRY · модерен C# · BCL-first engineering', aiCard: 'AI-assisted инженеринг', aiBody: 'Архитектурни правила · агенти · автоматизирано ревю · разработка с документация · контролирано генериране на код', yarpCard: 'YARP Reverse Proxy', yarpBody: 'Routing · transforms · автентикация и авторизация · health checks · forwarding · диагностика' },
    about: { metaTitle: 'За мен', eyebrow: 'За мен', title: 'Software Engineer / .NET Architect', lede: 'Backend и full-stack инженеринг с фокус върху ясни домейн граници, поддържаема архитектура и production-oriented софтуер.', focus: 'Фокус', focusBody: '.NET backend системи · домейн архитектура · SaaS · compliance · distributed systems · AI инфраструктура · cross-platform .NET', principles: 'Инженерни принципи', principlesBody: 'Прост код · ясни домейн граници · documentation-driven development · тестируеми vertical slices · прагматично използване на AI', statement: 'Целта е проста: архитектурата да се разбира от кода, продуктът да се разбира от UX-а, а инженерните решения да се разбират от документацията.' }
  },
  ru: {
    header: { primaryNavigation: 'Основная навигация', projects: 'Проекты', engineering: 'Инженерия', about: 'Обо мне' },
    meta: { titleTemplate: '{{title}} · YARP.DEV' },
    home: { metaTitle: 'Инженерия, продукты и техническая документация', heroEyebrow: 'Разработка программного обеспечения открыто', heroTitle: 'Реальные продукты, а не демонстрационные проекты.', heroLede: 'Ориентированная на production .NET-разработка, доменная архитектура, продуктовая разработка и техническая документация — на примере реальных систем и инженерных решений.', exploreProjects: 'Смотреть проекты', exploreEngineering: 'Смотреть инженерные практики', readDocs: 'Документация YARP', projectsEyebrow: 'Продукты', projectsTitle: 'Системы вокруг реальных предметных областей.', viewProject: 'Открыть проект', engineeringEyebrow: 'Инженерный фокус', engineeringTitle: 'Архитектура видна в самой работе.', practiceEyebrow: 'Инженерия на практике', practiceTitle: 'От постановки задачи до эксплуатации.', docsEyebrow: 'Документация', docsTitle: 'Документация — часть инженерного результата.', docsBody: 'YARP.DEV сохраняет существующие руководства Microsoft YARP как важную часть сайта и дополняет их материалами по архитектуре продуктов и инженерным практикам.', exploreDocs: 'Открыть документацию', footerAttribution: 'Документация Microsoft YARP адаптирована из Microsoft Learn по лицензии CC BY 4.0. YARP.DEV — независимый инженерный и документационный сайт.', footerSourceProject: 'Microsoft YARP на GitHub ↗', focusBackend: '.NET и backend', focusBackendBody: 'ASP.NET Core · EF Core · Aspire · OpenTelemetry · PostgreSQL · SQL Server', focusArchitecture: 'Архитектура', focusArchitectureBody: 'DDD · CQRS · модульный монолит · Vertical Slice · bounded contexts', focusProducts: 'Продукты и UX', focusProductsBody: 'Blazor · MAUI · корпоративные процессы · мультитенантность · compliance-системы', focusAi: 'AI-инфраструктура', focusAiBody: 'AI-шлюзы · локальные модели · облачный fallback · RAG · инструменты · наблюдаемость' },
    process: { aria: 'Инженерный поток от проблемы до эксплуатации', problem: 'Проблема', domain: 'Домен', architecture: 'Архитектура', ux: 'UX', api: 'API', implementation: 'Реализация', tests: 'Тесты', operations: 'Эксплуатация' },
    projects: { metaTitle: 'Проекты', eyebrow: 'Продуктовая инженерия', title: 'Проекты', lede: 'Портфолио реальных продуктовых доменов, архитектурных решений и реализации — как системы, а не список технологий.', problem: 'Проблема', architecture: 'Архитектура', viewProject: 'Открыть проект' },
    projectDetail: { allProjects: 'Все проекты', technicalDocs: 'Техническая документация', problem: 'Проблема', problemTitle: 'Какую задачу решает продукт', users: 'Пользователи', usersTitle: 'Для кого предназначена система', architecture: 'Архитектура', architectureTitle: 'Как устроена система', patterns: 'Паттерны и границы', frontend: 'Frontend', backend: 'Backend', infrastructure: 'Инфраструктура', engineering: 'Инженерные особенности', engineeringTitle: 'Задачи, которые стоит показать' },
    engineering: { metaTitle: 'Инженерия', eyebrow: 'Инженерная практика', title: 'Архитектура через работающие системы.', lede: 'Это не CV со списком технологий. Проекты показывают, как доменное моделирование, современный .NET, надежность, frontend-архитектура и AI-assisted разработка соединяются в production-ориентированных системах.', practiceEyebrow: 'Модель поставки', practiceTitle: 'Инженерия как связанная система.', architectureCard: 'Архитектура', architectureBody: 'DDD · CQRS · модульный монолит · Vertical Slice · bounded contexts', dotnetCard: '.NET', dotnetBody: 'ASP.NET Core · EF Core · Blazor · MAUI · Aspire · OpenTelemetry', reliabilityCard: 'Надежность', reliabilityBody: 'Result Pattern · идемпотентность · оптимистическая конкуренция · outbox · устойчивость · наблюдаемость', qualityCard: 'Качество кода', qualityBody: 'Clean Code · KISS · YAGNI · DRY · современный C# · BCL-first подход', aiCard: 'AI-assisted разработка', aiBody: 'Архитектурные правила · агенты · автоматизированное ревью · разработка с документацией · контролируемая генерация кода', yarpCard: 'YARP Reverse Proxy', yarpBody: 'Маршрутизация · трансформации · аутентификация и авторизация · проверки здоровья · forwarding · диагностика' },
    about: { metaTitle: 'Обо мне', eyebrow: 'Обо мне', title: 'Software Engineer / .NET Architect', lede: 'Backend- и full-stack-разработка с фокусом на явных доменных границах, поддерживаемой архитектуре и production-ориентированном ПО.', focus: 'Фокус', focusBody: '.NET backend-системы · доменная архитектура · SaaS · compliance · распределенные системы · AI-инфраструктура · кроссплатформенный .NET', principles: 'Инженерные принципы', principlesBody: 'Простой код · явные доменные границы · разработка через документацию · тестируемые vertical slices · прагматичное использование AI', statement: 'Цель проста: архитектура должна быть понятна из кода, продукт — из UX, а инженерные решения — из документации.' }
  },
  fr: {
    header: { primaryNavigation: 'Navigation principale', projects: 'Projets', engineering: 'Ingénierie', about: 'À propos' },
    meta: { titleTemplate: '{{title}} · YARP.DEV' },
    home: { metaTitle: 'Ingénierie, produits et documentation technique', heroEyebrow: 'Ingénierie logicielle en public', heroTitle: 'Des produits réels, pas des projets de démonstration.', heroLede: 'Ingénierie .NET orientée production, architecture métier, développement produit et documentation technique — illustrés par des systèmes et des décisions d’ingénierie réels.', exploreProjects: 'Explorer les projets', exploreEngineering: 'Explorer l’ingénierie', readDocs: 'Lire la documentation YARP', projectsEyebrow: 'Produits', projectsTitle: 'Des systèmes construits autour de domaines réels.', viewProject: 'Voir le projet', engineeringEyebrow: 'Axes d’ingénierie', engineeringTitle: 'L’architecture est visible dans le travail.', practiceEyebrow: 'Ingénierie en pratique', practiceTitle: 'Du cadrage du problème aux opérations.', docsEyebrow: 'Documentation', docsTitle: 'La documentation fait partie du résultat d’ingénierie.', docsBody: 'YARP.DEV conserve les guides Microsoft YARP existants comme contenu de premier plan tout en ajoutant des contenus sélectionnés sur l’architecture produit et l’ingénierie.', exploreDocs: 'Explorer la documentation', footerAttribution: 'La documentation Microsoft YARP est adaptée de Microsoft Learn sous licence CC BY 4.0. YARP.DEV est un site indépendant d’ingénierie et de documentation.', footerSourceProject: 'Microsoft YARP sur GitHub ↗', focusBackend: '.NET & backend', focusBackendBody: 'ASP.NET Core · EF Core · Aspire · OpenTelemetry · PostgreSQL · SQL Server', focusArchitecture: 'Architecture', focusArchitectureBody: 'DDD · CQRS · monolithe modulaire · Vertical Slice · bounded contexts', focusProducts: 'Produits & UX', focusProductsBody: 'Blazor · MAUI · workflows d’entreprise · multi-tenancy · systèmes de conformité', focusAi: 'Infrastructure IA', focusAiBody: 'Passerelles IA · modèles locaux · repli cloud · RAG · outils · observabilité' },
    process: { aria: 'Flux d’ingénierie du problème aux opérations', problem: 'Problème', domain: 'Domaine', architecture: 'Architecture', ux: 'UX', api: 'API', implementation: 'Implémentation', tests: 'Tests', operations: 'Opérations' },
    projects: { metaTitle: 'Projets', eyebrow: 'Ingénierie produit', title: 'Projets', lede: 'Un portefeuille de domaines produit réels, de décisions d’architecture et de travail d’implémentation — présenté comme des systèmes plutôt qu’une liste de technologies.', problem: 'Problème', architecture: 'Architecture', viewProject: 'Voir le projet' },
    projectDetail: { allProjects: 'Tous les projets', technicalDocs: 'Documentation technique', problem: 'Problème', problemTitle: 'Ce que le produit cherche à résoudre', users: 'Utilisateurs', usersTitle: 'À qui le système s’adresse', architecture: 'Architecture', architectureTitle: 'Comment le système est structuré', patterns: 'Patterns et frontières', frontend: 'Frontend', backend: 'Backend', infrastructure: 'Infrastructure', engineering: 'Points forts d’ingénierie', engineeringTitle: 'Des problèmes qui méritent d’être montrés' },
    engineering: { metaTitle: 'Ingénierie', eyebrow: 'Pratique d’ingénierie', title: 'L’architecture à travers des systèmes fonctionnels.', lede: 'L’objectif n’est pas un inventaire de technologies façon CV. Le travail montre comment la modélisation métier, le .NET moderne, la fiabilité, l’architecture frontend et le développement assisté par IA s’intègrent dans des systèmes orientés production.', practiceEyebrow: 'Modèle de livraison', practiceTitle: 'L’ingénierie comme système connecté.', architectureCard: 'Architecture', architectureBody: 'DDD · CQRS · monolithe modulaire · Vertical Slice · bounded contexts', dotnetCard: '.NET', dotnetBody: 'ASP.NET Core · EF Core · Blazor · MAUI · Aspire · OpenTelemetry', reliabilityCard: 'Fiabilité', reliabilityBody: 'Result Pattern · idempotence · concurrence optimiste · outbox · résilience · observabilité', qualityCard: 'Qualité du code', qualityBody: 'Clean Code · KISS · YAGNI · DRY · C# moderne · ingénierie BCL-first', aiCard: 'Ingénierie assistée par IA', aiBody: 'Règles d’architecture · agents · revue automatisée · implémentation guidée par la documentation · génération de code contrôlée', yarpCard: 'YARP Reverse Proxy', yarpBody: 'Routage · transformations · authentification et autorisation · health checks · forwarding · diagnostics' },
    about: { metaTitle: 'À propos', eyebrow: 'À propos', title: 'Software Engineer / .NET Architect', lede: 'Ingénierie backend et full-stack axée sur des frontières métier explicites, une architecture maintenable et des logiciels orientés production.', focus: 'Domaines', focusBody: 'Systèmes backend .NET · architecture métier · SaaS · conformité · systèmes distribués · infrastructure IA · .NET multiplateforme', principles: 'Principes d’ingénierie', principlesBody: 'Code simple · frontières métier explicites · développement guidé par la documentation · vertical slices testables · usage pragmatique de l’IA', statement: 'L’objectif est simple : rendre l’architecture compréhensible dans le code, le produit compréhensible dans l’UX et les décisions d’ingénierie compréhensibles dans la documentation.' }
  },
  el: {
    header: { primaryNavigation: 'Κύρια πλοήγηση', projects: 'Έργα', engineering: 'Μηχανική', about: 'Σχετικά' },
    meta: { titleTemplate: '{{title}} · YARP.DEV' },
    home: { metaTitle: 'Μηχανική, προϊόντα και τεχνική τεκμηρίωση', heroEyebrow: 'Μηχανική λογισμικού δημόσια', heroTitle: 'Πραγματικά προϊόντα, όχι demo projects.', heroLede: 'Μηχανική .NET με προσανατολισμό στην παραγωγή, αρχιτεκτονική domain, ανάπτυξη προϊόντων και τεχνική τεκμηρίωση — μέσα από πραγματικά συστήματα και αποφάσεις μηχανικής.', exploreProjects: 'Εξερεύνηση έργων', exploreEngineering: 'Εξερεύνηση μηχανικής', readDocs: 'Τεκμηρίωση YARP', projectsEyebrow: 'Προϊόντα', projectsTitle: 'Συστήματα χτισμένα γύρω από πραγματικά domains.', viewProject: 'Προβολή έργου', engineeringEyebrow: 'Εστίαση μηχανικής', engineeringTitle: 'Η αρχιτεκτονική φαίνεται στην ίδια την εργασία.', practiceEyebrow: 'Μηχανική στην πράξη', practiceTitle: 'Από τον ορισμό του προβλήματος έως τις λειτουργίες.', docsEyebrow: 'Τεκμηρίωση', docsTitle: 'Η τεκμηρίωση αποτελεί μέρος του αποτελέσματος της μηχανικής.', docsBody: 'Το YARP.DEV διατηρεί τους υπάρχοντες οδηγούς Microsoft YARP ως βασικό περιεχόμενο και προσθέτει επιλεγμένο υλικό για αρχιτεκτονική προϊόντων και μηχανική.', exploreDocs: 'Εξερεύνηση τεκμηρίωσης', footerAttribution: 'Η τεκμηρίωση Microsoft YARP είναι προσαρμοσμένη από το Microsoft Learn με άδεια CC BY 4.0. Το YARP.DEV είναι ανεξάρτητος ιστότοπος μηχανικής και τεκμηρίωσης.', footerSourceProject: 'Microsoft YARP στο GitHub ↗', focusBackend: '.NET & backend', focusBackendBody: 'ASP.NET Core · EF Core · Aspire · OpenTelemetry · PostgreSQL · SQL Server', focusArchitecture: 'Αρχιτεκτονική', focusArchitectureBody: 'DDD · CQRS · Modular Monolith · Vertical Slice · bounded contexts', focusProducts: 'Προϊόντα & UX', focusProductsBody: 'Blazor · MAUI · enterprise workflows · multi-tenancy · συστήματα συμμόρφωσης', focusAi: 'Υποδομή AI', focusAiBody: 'AI gateways · τοπικά μοντέλα · cloud fallback · RAG · εργαλεία · παρατηρησιμότητα' },
    process: { aria: 'Ροή μηχανικής από το πρόβλημα έως τις λειτουργίες', problem: 'Πρόβλημα', domain: 'Domain', architecture: 'Αρχιτεκτονική', ux: 'UX', api: 'API', implementation: 'Υλοποίηση', tests: 'Δοκιμές', operations: 'Λειτουργίες' },
    projects: { metaTitle: 'Έργα', eyebrow: 'Μηχανική προϊόντος', title: 'Έργα', lede: 'Ένα portfolio πραγματικών product domains, αρχιτεκτονικών αποφάσεων και υλοποίησης — παρουσιασμένο ως συστήματα και όχι ως λίστα τεχνολογιών.', problem: 'Πρόβλημα', architecture: 'Αρχιτεκτονική', viewProject: 'Προβολή έργου' },
    projectDetail: { allProjects: 'Όλα τα έργα', technicalDocs: 'Τεχνική τεκμηρίωση', problem: 'Πρόβλημα', problemTitle: 'Τι λύνει το προϊόν', users: 'Χρήστες', usersTitle: 'Ποιους εξυπηρετεί το σύστημα', architecture: 'Αρχιτεκτονική', architectureTitle: 'Πώς είναι δομημένο το σύστημα', patterns: 'Patterns και όρια', frontend: 'Frontend', backend: 'Backend', infrastructure: 'Υποδομή', engineering: 'Σημεία μηχανικής', engineeringTitle: 'Προβλήματα που αξίζει να παρουσιαστούν' },
    engineering: { metaTitle: 'Μηχανική', eyebrow: 'Πρακτική μηχανικής', title: 'Αρχιτεκτονική μέσα από λειτουργικά συστήματα.', lede: 'Η εστίαση δεν είναι μια λίστα τεχνολογιών τύπου CV. Η δουλειά δείχνει πώς η μοντελοποίηση domain, το σύγχρονο .NET, η αξιοπιστία, η frontend αρχιτεκτονική και η ανάπτυξη με AI συνεργάζονται σε production-oriented συστήματα.', practiceEyebrow: 'Μοντέλο παράδοσης', practiceTitle: 'Η μηχανική ως συνδεδεμένο σύστημα.', architectureCard: 'Αρχιτεκτονική', architectureBody: 'DDD · CQRS · Modular Monolith · Vertical Slice · bounded contexts', dotnetCard: '.NET', dotnetBody: 'ASP.NET Core · EF Core · Blazor · MAUI · Aspire · OpenTelemetry', reliabilityCard: 'Αξιοπιστία', reliabilityBody: 'Result Pattern · idempotency · optimistic concurrency · outbox · resilience · observability', qualityCard: 'Ποιότητα κώδικα', qualityBody: 'Clean Code · KISS · YAGNI · DRY · σύγχρονο C# · BCL-first engineering', aiCard: 'Μηχανική με υποστήριξη AI', aiBody: 'Κανόνες αρχιτεκτονικής · agents · αυτοματοποιημένο review · υλοποίηση με βάση την τεκμηρίωση · ελεγχόμενη παραγωγή κώδικα', yarpCard: 'YARP Reverse Proxy', yarpBody: 'Routing · transforms · authentication & authorization · health checks · forwarding · diagnostics' },
    about: { metaTitle: 'Σχετικά', eyebrow: 'Σχετικά', title: 'Software Engineer / .NET Architect', lede: 'Backend και full-stack μηχανική με έμφαση σε σαφή domain boundaries, συντηρήσιμη αρχιτεκτονική και production-oriented λογισμικό.', focus: 'Εστίαση', focusBody: '.NET backend συστήματα · αρχιτεκτονική domain · SaaS · compliance · κατανεμημένα συστήματα · AI υποδομή · cross-platform .NET', principles: 'Αρχές μηχανικής', principlesBody: 'Απλός κώδικας · σαφή domain boundaries · documentation-driven development · testable vertical slices · πρακτική χρήση AI', statement: 'Ο στόχος είναι απλός: η αρχιτεκτονική να γίνεται κατανοητή από τον κώδικα, το προϊόν από το UX και οι αποφάσεις μηχανικής από την τεκμηρίωση.' }
  },
  es: {
    header: { primaryNavigation: 'Navegación principal', projects: 'Proyectos', engineering: 'Ingeniería', about: 'Acerca de' },
    meta: { titleTemplate: '{{title}} · YARP.DEV' },
    home: { metaTitle: 'Ingeniería, productos y documentación técnica', heroEyebrow: 'Ingeniería de software en público', heroTitle: 'Productos reales, no proyectos de demostración.', heroLede: 'Ingeniería .NET orientada a producción, arquitectura de dominio, desarrollo de producto y documentación técnica — demostrados mediante sistemas y decisiones de ingeniería reales.', exploreProjects: 'Explorar proyectos', exploreEngineering: 'Explorar ingeniería', readDocs: 'Leer documentación de YARP', projectsEyebrow: 'Productos', projectsTitle: 'Sistemas construidos alrededor de dominios reales.', viewProject: 'Ver proyecto', engineeringEyebrow: 'Enfoque de ingeniería', engineeringTitle: 'La arquitectura es visible en el trabajo.', practiceEyebrow: 'Ingeniería en la práctica', practiceTitle: 'Del planteamiento del problema a las operaciones.', docsEyebrow: 'Documentación', docsTitle: 'La documentación forma parte del resultado de ingeniería.', docsBody: 'YARP.DEV mantiene las guías existentes de Microsoft YARP como contenido de primer nivel y añade material seleccionado sobre arquitectura de producto e ingeniería.', exploreDocs: 'Explorar documentación', footerAttribution: 'La documentación de Microsoft YARP está adaptada de Microsoft Learn bajo CC BY 4.0. YARP.DEV es un sitio independiente de ingeniería y documentación.', footerSourceProject: 'Microsoft YARP en GitHub ↗', focusBackend: '.NET y backend', focusBackendBody: 'ASP.NET Core · EF Core · Aspire · OpenTelemetry · PostgreSQL · SQL Server', focusArchitecture: 'Arquitectura', focusArchitectureBody: 'DDD · CQRS · monolito modular · Vertical Slice · bounded contexts', focusProducts: 'Productos y UX', focusProductsBody: 'Blazor · MAUI · flujos empresariales · multi-tenancy · sistemas de compliance', focusAi: 'Infraestructura de IA', focusAiBody: 'Gateways de IA · modelos locales · fallback en la nube · RAG · herramientas · observabilidad' },
    process: { aria: 'Flujo de ingeniería desde el problema hasta las operaciones', problem: 'Problema', domain: 'Dominio', architecture: 'Arquitectura', ux: 'UX', api: 'API', implementation: 'Implementación', tests: 'Pruebas', operations: 'Operaciones' },
    projects: { metaTitle: 'Proyectos', eyebrow: 'Ingeniería de producto', title: 'Proyectos', lede: 'Un portfolio de dominios de producto reales, decisiones de arquitectura y trabajo de implementación — presentado como sistemas y no como una lista de tecnologías.', problem: 'Problema', architecture: 'Arquitectura', viewProject: 'Ver proyecto' },
    projectDetail: { allProjects: 'Todos los proyectos', technicalDocs: 'Documentación técnica', problem: 'Problema', problemTitle: 'Qué problema resuelve el producto', users: 'Usuarios', usersTitle: 'A quién sirve el sistema', architecture: 'Arquitectura', architectureTitle: 'Cómo está estructurado el sistema', patterns: 'Patrones y límites', frontend: 'Frontend', backend: 'Backend', infrastructure: 'Infraestructura', engineering: 'Aspectos destacados de ingeniería', engineeringTitle: 'Problemas que merece la pena mostrar' },
    engineering: { metaTitle: 'Ingeniería', eyebrow: 'Práctica de ingeniería', title: 'Arquitectura a través de sistemas reales.', lede: 'El foco no es un inventario de tecnologías estilo CV. El trabajo muestra cómo el modelado de dominio, .NET moderno, fiabilidad, arquitectura frontend y desarrollo asistido por IA encajan en sistemas orientados a producción.', practiceEyebrow: 'Modelo de entrega', practiceTitle: 'La ingeniería como un sistema conectado.', architectureCard: 'Arquitectura', architectureBody: 'DDD · CQRS · monolito modular · Vertical Slice · bounded contexts', dotnetCard: '.NET', dotnetBody: 'ASP.NET Core · EF Core · Blazor · MAUI · Aspire · OpenTelemetry', reliabilityCard: 'Fiabilidad', reliabilityBody: 'Result Pattern · idempotencia · concurrencia optimista · outbox · resiliencia · observabilidad', qualityCard: 'Calidad de código', qualityBody: 'Clean Code · KISS · YAGNI · DRY · C# moderno · ingeniería BCL-first', aiCard: 'Ingeniería asistida por IA', aiBody: 'Reglas de arquitectura · agentes · revisión automatizada · implementación guiada por documentación · generación controlada de código', yarpCard: 'YARP Reverse Proxy', yarpBody: 'Enrutamiento · transformaciones · autenticación y autorización · health checks · forwarding · diagnóstico' },
    about: { metaTitle: 'Acerca de', eyebrow: 'Acerca de', title: 'Software Engineer / .NET Architect', lede: 'Ingeniería backend y full-stack centrada en límites de dominio explícitos, arquitectura mantenible y software orientado a producción.', focus: 'Enfoque', focusBody: 'Sistemas backend .NET · arquitectura de dominio · SaaS · compliance · sistemas distribuidos · infraestructura de IA · .NET multiplataforma', principles: 'Principios de ingeniería', principlesBody: 'Código simple · límites de dominio explícitos · desarrollo guiado por documentación · vertical slices testeables · uso pragmático de IA', statement: 'El objetivo es simple: que la arquitectura se entienda en el código, el producto en la UX y las decisiones de ingeniería en la documentación.' }
  },
  de: {
    header: { primaryNavigation: 'Hauptnavigation', projects: 'Projekte', engineering: 'Engineering', about: 'Über mich' },
    meta: { titleTemplate: '{{title}} · YARP.DEV' },
    home: { metaTitle: 'Engineering, Produkte und technische Dokumentation', heroEyebrow: 'Software Engineering öffentlich', heroTitle: 'Echte Produkte statt Demo-Projekte.', heroLede: 'Produktionsorientiertes .NET Engineering, Domänenarchitektur, Produktentwicklung und technische Dokumentation — gezeigt anhand realer Systeme und Engineering-Entscheidungen.', exploreProjects: 'Projekte entdecken', exploreEngineering: 'Engineering entdecken', readDocs: 'YARP-Dokumentation lesen', projectsEyebrow: 'Produkte', projectsTitle: 'Systeme rund um reale Domänen.', viewProject: 'Projekt ansehen', engineeringEyebrow: 'Engineering-Fokus', engineeringTitle: 'Die Architektur ist in der Arbeit sichtbar.', practiceEyebrow: 'Engineering in der Praxis', practiceTitle: 'Von der Problemdefinition bis zum Betrieb.', docsEyebrow: 'Dokumentation', docsTitle: 'Dokumentation ist Teil des Engineering-Ergebnisses.', docsBody: 'YARP.DEV hält die bestehenden Microsoft-YARP-Leitfäden als erstklassigen Inhalt verfügbar und ergänzt kuratierte Inhalte zu Produktarchitektur und Engineering.', exploreDocs: 'Dokumentation entdecken', footerAttribution: 'Die Microsoft-YARP-Dokumentation basiert auf Microsoft Learn unter CC BY 4.0. YARP.DEV ist eine unabhängige Engineering- und Dokumentationsseite.', footerSourceProject: 'Microsoft YARP auf GitHub ↗', focusBackend: '.NET & Backend', focusBackendBody: 'ASP.NET Core · EF Core · Aspire · OpenTelemetry · PostgreSQL · SQL Server', focusArchitecture: 'Architektur', focusArchitectureBody: 'DDD · CQRS · Modularer Monolith · Vertical Slice · Bounded Contexts', focusProducts: 'Produkte & UX', focusProductsBody: 'Blazor · MAUI · Enterprise-Workflows · Multi-Tenancy · Compliance-Systeme', focusAi: 'KI-Infrastruktur', focusAiBody: 'KI-Gateways · lokale Modelle · Cloud-Fallback · RAG · Tools · Observability' },
    process: { aria: 'Engineering-Ablauf vom Problem bis zum Betrieb', problem: 'Problem', domain: 'Domäne', architecture: 'Architektur', ux: 'UX', api: 'API', implementation: 'Implementierung', tests: 'Tests', operations: 'Betrieb' },
    projects: { metaTitle: 'Projekte', eyebrow: 'Product Engineering', title: 'Projekte', lede: 'Ein Portfolio realer Produktdomänen, Architekturentscheidungen und Implementierungsarbeit — als Systeme statt als Technologieliste präsentiert.', problem: 'Problem', architecture: 'Architektur', viewProject: 'Projekt ansehen' },
    projectDetail: { allProjects: 'Alle Projekte', technicalDocs: 'Technische Dokumentation', problem: 'Problem', problemTitle: 'Welches Problem das Produkt löst', users: 'Benutzer', usersTitle: 'Für wen das System gedacht ist', architecture: 'Architektur', architectureTitle: 'Wie das System aufgebaut ist', patterns: 'Muster & Grenzen', frontend: 'Frontend', backend: 'Backend', infrastructure: 'Infrastruktur', engineering: 'Engineering-Highlights', engineeringTitle: 'Probleme, die es wert sind, gezeigt zu werden' },
    engineering: { metaTitle: 'Engineering', eyebrow: 'Engineering-Praxis', title: 'Architektur durch funktionierende Systeme.', lede: 'Der Fokus liegt nicht auf einer CV-artigen Technologieliste. Die Arbeit zeigt, wie Domänenmodellierung, modernes .NET, Zuverlässigkeit, Frontend-Architektur und KI-gestützte Entwicklung in produktionsorientierten Systemen zusammenspielen.', practiceEyebrow: 'Delivery-Modell', practiceTitle: 'Engineering als verbundenes System.', architectureCard: 'Architektur', architectureBody: 'DDD · CQRS · Modularer Monolith · Vertical Slice · Bounded Contexts', dotnetCard: '.NET', dotnetBody: 'ASP.NET Core · EF Core · Blazor · MAUI · Aspire · OpenTelemetry', reliabilityCard: 'Zuverlässigkeit', reliabilityBody: 'Result Pattern · Idempotenz · optimistische Nebenläufigkeit · Outbox · Resilienz · Observability', qualityCard: 'Codequalität', qualityBody: 'Clean Code · KISS · YAGNI · DRY · modernes C# · BCL-first Engineering', aiCard: 'KI-gestütztes Engineering', aiBody: 'Architekturregeln · Agents · automatisierte Reviews · dokumentationsgestützte Implementierung · kontrollierte Codegenerierung', yarpCard: 'YARP Reverse Proxy', yarpBody: 'Routing · Transformationen · Authentifizierung & Autorisierung · Health Checks · Forwarding · Diagnose' },
    about: { metaTitle: 'Über mich', eyebrow: 'Über mich', title: 'Software Engineer / .NET Architect', lede: 'Backend- und Full-Stack-Engineering mit Fokus auf explizite Domänengrenzen, wartbare Architektur und produktionsorientierte Software.', focus: 'Fokus', focusBody: '.NET-Backend-Systeme · Domänenarchitektur · SaaS · Compliance · verteilte Systeme · KI-Infrastruktur · plattformübergreifendes .NET', principles: 'Engineering-Prinzipien', principlesBody: 'Einfacher Code · explizite Domänengrenzen · dokumentationsgetriebene Entwicklung · testbare Vertical Slices · pragmatischer KI-Einsatz', statement: 'Das Ziel ist einfach: Die Architektur soll im Code, das Produkt in der UX und die Engineering-Entscheidungen in der Dokumentation verständlich sein.' }
  },
  'pt-BR': {
    header: { primaryNavigation: 'Navegação principal', projects: 'Projetos', engineering: 'Engenharia', about: 'Sobre' },
    meta: { titleTemplate: '{{title}} · YARP.DEV' },
    home: { metaTitle: 'Engenharia, produtos e documentação técnica', heroEyebrow: 'Engenharia de software em público', heroTitle: 'Produtos reais, não projetos de demonstração.', heroLede: 'Engenharia .NET orientada à produção, arquitetura de domínio, desenvolvimento de produto e documentação técnica — demonstrados por sistemas e decisões reais de engenharia.', exploreProjects: 'Explorar projetos', exploreEngineering: 'Explorar engenharia', readDocs: 'Ler documentação do YARP', projectsEyebrow: 'Produtos', projectsTitle: 'Sistemas construídos em torno de domínios reais.', viewProject: 'Ver projeto', engineeringEyebrow: 'Foco de engenharia', engineeringTitle: 'A arquitetura aparece no próprio trabalho.', practiceEyebrow: 'Engenharia na prática', practiceTitle: 'Do enquadramento do problema às operações.', docsEyebrow: 'Documentação', docsTitle: 'A documentação faz parte do resultado de engenharia.', docsBody: 'O YARP.DEV mantém os guias existentes do Microsoft YARP como conteúdo de primeira classe e acrescenta material selecionado sobre arquitetura de produto e engenharia.', exploreDocs: 'Explorar documentação', footerAttribution: 'A documentação do Microsoft YARP é adaptada do Microsoft Learn sob CC BY 4.0. YARP.DEV é um site independente de engenharia e documentação.', footerSourceProject: 'Microsoft YARP no GitHub ↗', focusBackend: '.NET e backend', focusBackendBody: 'ASP.NET Core · EF Core · Aspire · OpenTelemetry · PostgreSQL · SQL Server', focusArchitecture: 'Arquitetura', focusArchitectureBody: 'DDD · CQRS · Monólito Modular · Vertical Slice · bounded contexts', focusProducts: 'Produtos e UX', focusProductsBody: 'Blazor · MAUI · fluxos empresariais · multi-tenancy · sistemas de compliance', focusAi: 'Infraestrutura de IA', focusAiBody: 'Gateways de IA · modelos locais · fallback na nuvem · RAG · ferramentas · observabilidade' },
    process: { aria: 'Fluxo de engenharia do problema às operações', problem: 'Problema', domain: 'Domínio', architecture: 'Arquitetura', ux: 'UX', api: 'API', implementation: 'Implementação', tests: 'Testes', operations: 'Operações' },
    projects: { metaTitle: 'Projetos', eyebrow: 'Engenharia de produto', title: 'Projetos', lede: 'Um portfólio de domínios de produto reais, decisões de arquitetura e trabalho de implementação — apresentado como sistemas, não como uma lista de tecnologias.', problem: 'Problema', architecture: 'Arquitetura', viewProject: 'Ver projeto' },
    projectDetail: { allProjects: 'Todos os projetos', technicalDocs: 'Documentação técnica', problem: 'Problema', problemTitle: 'O que o produto está resolvendo', users: 'Usuários', usersTitle: 'Quem o sistema atende', architecture: 'Arquitetura', architectureTitle: 'Como o sistema é estruturado', patterns: 'Padrões e limites', frontend: 'Frontend', backend: 'Backend', infrastructure: 'Infraestrutura', engineering: 'Destaques de engenharia', engineeringTitle: 'Problemas que valem a pena mostrar' },
    engineering: { metaTitle: 'Engenharia', eyebrow: 'Prática de engenharia', title: 'Arquitetura por meio de sistemas funcionais.', lede: 'O foco não é um inventário de tecnologias no estilo CV. O trabalho mostra como modelagem de domínio, .NET moderno, confiabilidade, arquitetura frontend e desenvolvimento assistido por IA se encaixam em sistemas orientados à produção.', practiceEyebrow: 'Modelo de entrega', practiceTitle: 'Engenharia como um sistema conectado.', architectureCard: 'Arquitetura', architectureBody: 'DDD · CQRS · Monólito Modular · Vertical Slice · bounded contexts', dotnetCard: '.NET', dotnetBody: 'ASP.NET Core · EF Core · Blazor · MAUI · Aspire · OpenTelemetry', reliabilityCard: 'Confiabilidade', reliabilityBody: 'Result Pattern · idempotência · concorrência otimista · outbox · resiliência · observabilidade', qualityCard: 'Qualidade de código', qualityBody: 'Clean Code · KISS · YAGNI · DRY · C# moderno · engenharia BCL-first', aiCard: 'Engenharia assistida por IA', aiBody: 'Regras de arquitetura · agentes · revisão automatizada · implementação guiada por documentação · geração controlada de código', yarpCard: 'YARP Reverse Proxy', yarpBody: 'Roteamento · transformações · autenticação e autorização · health checks · forwarding · diagnóstico' },
    about: { metaTitle: 'Sobre', eyebrow: 'Sobre', title: 'Software Engineer / .NET Architect', lede: 'Engenharia backend e full-stack focada em limites de domínio explícitos, arquitetura sustentável e software orientado à produção.', focus: 'Foco', focusBody: 'Sistemas backend .NET · arquitetura de domínio · SaaS · compliance · sistemas distribuídos · infraestrutura de IA · .NET multiplataforma', principles: 'Princípios de engenharia', principlesBody: 'Código simples · limites de domínio explícitos · desenvolvimento orientado por documentação · vertical slices testáveis · uso pragmático de IA', statement: 'O objetivo é simples: tornar a arquitetura compreensível no código, o produto compreensível na UX e as decisões de engenharia compreensíveis na documentação.' }
  },
  'zh-Hans': {
    header: { primaryNavigation: '主导航', projects: '项目', engineering: '工程实践', about: '关于' },
    meta: { titleTemplate: '{{title}} · YARP.DEV' },
    home: { metaTitle: '工程、产品与技术文档', heroEyebrow: '公开的软件工程实践', heroTitle: '构建真实产品，而不是演示项目。', heroLede: '面向生产的 .NET 工程、领域架构、产品开发与技术文档——通过真实系统和工程决策来展示。', exploreProjects: '浏览项目', exploreEngineering: '浏览工程实践', readDocs: '阅读 YARP 文档', projectsEyebrow: '产品', projectsTitle: '围绕真实业务领域构建的系统。', viewProject: '查看项目', engineeringEyebrow: '工程重点', engineeringTitle: '架构体现在实际工作中。', practiceEyebrow: '工程实践', practiceTitle: '从问题定义到生产运维。', docsEyebrow: '文档', docsTitle: '文档本身就是工程产出的一部分。', docsBody: 'YARP.DEV 保留现有 Microsoft YARP 指南作为核心内容，同时增加精选的产品架构与工程实践资料。', exploreDocs: '浏览文档', footerAttribution: 'Microsoft YARP 文档改编自 Microsoft Learn，采用 CC BY 4.0 许可。YARP.DEV 是独立的工程与文档网站。', footerSourceProject: 'GitHub 上的 Microsoft YARP ↗', focusBackend: '.NET 与后端', focusBackendBody: 'ASP.NET Core · EF Core · Aspire · OpenTelemetry · PostgreSQL · SQL Server', focusArchitecture: '架构', focusArchitectureBody: 'DDD · CQRS · 模块化单体 · Vertical Slice · 限界上下文', focusProducts: '产品与 UX', focusProductsBody: 'Blazor · MAUI · 企业工作流 · 多租户 · 合规系统', focusAi: 'AI 基础设施', focusAiBody: 'AI 网关 · 本地模型 · 云端回退 · RAG · 工具 · 可观测性' },
    process: { aria: '从问题到运维的工程流程', problem: '问题', domain: '领域', architecture: '架构', ux: 'UX', api: 'API', implementation: '实现', tests: '测试', operations: '运维' },
    projects: { metaTitle: '项目', eyebrow: '产品工程', title: '项目', lede: '真实产品领域、架构决策与实现工作的组合——以系统形式呈现，而不是技术清单。', problem: '问题', architecture: '架构', viewProject: '查看项目' },
    projectDetail: { allProjects: '所有项目', technicalDocs: '技术文档', problem: '问题', problemTitle: '产品正在解决什么问题', users: '用户', usersTitle: '系统服务的对象', architecture: '架构', architectureTitle: '系统如何组织', patterns: '模式与边界', frontend: '前端', backend: '后端', infrastructure: '基础设施', engineering: '工程亮点', engineeringTitle: '值得展示的问题' },
    engineering: { metaTitle: '工程实践', eyebrow: '工程实践', title: '通过运行中的系统展示架构。', lede: '重点不是简历式的技术清单，而是展示领域建模、现代 .NET、可靠性、前端架构与 AI 辅助开发如何在面向生产的系统中协同工作。', practiceEyebrow: '交付模型', practiceTitle: '把工程视为一个互联系统。', architectureCard: '架构', architectureBody: 'DDD · CQRS · 模块化单体 · Vertical Slice · 限界上下文', dotnetCard: '.NET', dotnetBody: 'ASP.NET Core · EF Core · Blazor · MAUI · Aspire · OpenTelemetry', reliabilityCard: '可靠性', reliabilityBody: 'Result Pattern · 幂等性 · 乐观并发 · Outbox · 弹性 · 可观测性', qualityCard: '代码质量', qualityBody: 'Clean Code · KISS · YAGNI · DRY · 现代 C# · BCL-first 工程', aiCard: 'AI 辅助工程', aiBody: '架构规则 · agents · 自动化评审 · 文档辅助实现 · 受控代码生成', yarpCard: 'YARP Reverse Proxy', yarpBody: '路由 · 转换 · 身份验证与授权 · 健康检查 · 转发 · 诊断' },
    about: { metaTitle: '关于', eyebrow: '关于', title: 'Software Engineer / .NET Architect', lede: '专注于明确领域边界、可维护架构和面向生产软件的后端与全栈工程。', focus: '方向', focusBody: '.NET 后端系统 · 领域架构 · SaaS · 合规 · 分布式系统 · AI 基础设施 · 跨平台 .NET', principles: '工程原则', principlesBody: '简单代码 · 明确领域边界 · 文档驱动开发 · 可测试的 Vertical Slices · 务实使用 AI', statement: '目标很简单：让架构能从代码中读懂，让产品能从 UX 中理解，让工程决策能从文档中追溯。' }
  }
};
